"""
ToyTalk Backend — Nano Banana 2 이미지 생성 서비스
Stage 2: Nano Banana 2 (gemini-3.1-flash-image-preview) 아바타 생성
Stage 3: 품질 검증
"""

import logging
import math

logger = logging.getLogger(__name__)


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Hex → RGB"""
    h = hex_color.lstrip("#")
    if len(h) != 6:
        return (128, 128, 128)
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def calculate_color_similarity(hex1: str, hex2: str) -> float:
    """두 색상의 RGB 유사도 (0~1)"""
    try:
        r1, g1, b1 = _hex_to_rgb(hex1)
        r2, g2, b2 = _hex_to_rgb(hex2)
        distance = math.sqrt((r1 - r2) ** 2 + (g1 - g2) ** 2 + (b1 - b2) ** 2)
        max_distance = math.sqrt(255**2 * 3)
        return 1.0 - (distance / max_distance)
    except Exception:
        return 0.5


async def generate_avatar(analysis: dict) -> bytes:
    """
    Nano Banana 2 (gemini-3.1-flash-image-preview) 기반 2D 셀셰이딩 아바타 생성
    Returns: 이미지 바이트 (PNG)
    """
    try:
        from google import genai
        from config.settings import settings

        client = genai.Client(
            vertexai=True,
            project=settings.GOOGLE_CLOUD_PROJECT,
            location=settings.GOOGLE_CLOUD_LOCATION,
        )

        features_str = ", ".join(analysis.get("features", []))
        toy_type = analysis.get("type", "toy")
        primary_color = analysis.get("primaryColor", "#808080")
        expression = analysis.get("expression", "neutral")

        prompt = (
            f"Create a cute 2D cartoon avatar with cel-shading style of a {toy_type} plush toy character. "
            f"The character must have primary color {primary_color}. "
            f"Key features to preserve exactly: [{features_str}]. "
            f"Style: child-friendly animation character, soft rounded lines, warm and inviting. "
            f"The character should look like a friendly cartoon toy with a {expression} expression. "
            f"White or transparent background. Aspect ratio 1:1. "
            f"DO NOT add any accessories, clothing, or elements not described above. "
            f"Make it look like a character from a beloved children's animated show."
        )

        # Nano Banana 2 모델로 이미지 생성
        response = client.models.generate_content(
            model=settings.GEMINI_FLASH_EXP_MODEL,  # gemini-3.1-flash-image-preview (Nano Banana 2)
            contents=[prompt],
        )

        # 응답에서 이미지 바이트 추출
        for part in response.candidates[0].content.parts:
            if part.inline_data and part.inline_data.mime_type.startswith("image/"):
                return part.inline_data.data

        raise ValueError("No image generated by Nano Banana 2")

    except Exception as e:
        logger.error(f"Nano Banana 2 avatar generation failed: {e}")
        raise


async def generate_avatar_from_photo(photo_bytes: bytes, analysis: dict) -> bytes:
    """
    Nano Banana 2로 원본 사진 기반 아바타 생성 (이미지 편집 모드)
    원본 사진을 참조하여 더 정확한 아바타를 생성
    """
    try:
        from google import genai
        from config.settings import settings

        client = genai.Client(
            vertexai=True,
            project=settings.GOOGLE_CLOUD_PROJECT,
            location=settings.GOOGLE_CLOUD_LOCATION,
        )

        features_str = ", ".join(analysis.get("features", []))
        toy_type = analysis.get("type", "toy")

        prompt = (
            f"Transform this toy photo into a cute 2D cartoon avatar with cel-shading style. "
            f"This is a {toy_type} toy. "
            f"Keep the same colors and key features: [{features_str}]. "
            f"Make it look like a child-friendly cartoon character. "
            f"White background, 1:1 aspect ratio. "
            f"Preserve the toy's identity — a child should recognize their toy in this cartoon version."
        )

        # 원본 사진 + 프롬프트로 이미지 편집/변환
        response = client.models.generate_content(
            model=settings.GEMINI_FLASH_EXP_MODEL,
            contents=[
                genai.types.Part.from_bytes(data=photo_bytes, mime_type="image/jpeg"),
                prompt,
            ],
        )

        for part in response.candidates[0].content.parts:
            if part.inline_data and part.inline_data.mime_type.startswith("image/"):
                return part.inline_data.data

        raise ValueError("No image generated from photo")

    except Exception as e:
        logger.error(f"Photo-based avatar generation failed: {e}")
        raise


async def verify_avatar(original_analysis: dict, avatar_bytes: bytes) -> dict:
    """
    Stage 3: 생성된 아바타를 재분석하여 원본과 비교
    Returns: {"color_match_score", "feature_preservation_score", "passed"}
    """
    from services.gemini_vision import analyze_toy

    try:
        avatar_analysis = await analyze_toy(avatar_bytes)

        color_score = calculate_color_similarity(
            original_analysis.get("primaryColor", "#808080"),
            avatar_analysis.get("primaryColor", "#808080"),
        )

        original_features = set(original_analysis.get("features", []))
        avatar_features = set(avatar_analysis.get("features", []))
        feature_score = len(original_features & avatar_features) / max(
            len(original_features), 1
        )

        return {
            "color_match_score": color_score,
            "feature_preservation_score": feature_score,
            "passed": color_score >= 0.85 and feature_score >= 0.80,
        }
    except Exception as e:
        logger.error(f"Avatar verification failed: {e}")
        return {
            "color_match_score": 0.0,
            "feature_preservation_score": 0.0,
            "passed": False,
        }
